attwad/python-osc

- .gitignore
- pythonosc/dispatcher.py
- pythonosc/test/test_dispatcher.py
I wanted to be able to map addresses to more than one handler, and found this TODO in the dispatcher:
>  Check if we need to use a multimap instead, spec is a bit fuzzy about it...
It's not clear to me either whether a dispatcher is required by the spec to allow multiple mappings of the same address. But it made sense in my use case, so this pull request enables it.  So now handler1 and handler2 are both called by this dispatcher:
```Python
dispatcher.map("/foo/bar", handler1)
dispatcher.map("/foo/bar", handler2)
```
I used a defaultdict(list) instead of a multimap, since its in the standard library.
I changed handlers_for_address to return a generator rather than a list of handlers since the list comprehension was getting a little long to read quickly. This meant a few more of the …
> Changed Dispatcher.map to a default dict to support multiple mappings

- .travis.yml
- README.rst
- pythonosc/osc_server.py
This change adds an AsyncIOOSCUDPServer.  Its intended use is as an alternative to the existing threading/forking servers which uses the asyncio module.
The logic of _UDPHandler.handle was moved into a _handle function so the different datagram mechanisms of the socketserver servers and the asyncio server could use the same handling code.
The existing *OSCUDPServer classes all shared the same methods, so they were pushed into a superclass, OSCUDPServer.  There were no logical changes to them other than that refactor.
The new class can be used like this:
loop = asyncio.get_event_loop()
server = AsyncIOOSCUDPServer(server_address, dispatcher, loop)
server.serve()
loop.run_forever()
> added AsyncIOOSCUDPServer

- pythonosc/osc_message_builder.py
- pythonosc/test/test_osc_message_builder.py
No-args message didn't contain the empty typetag, and other software, like Max, couldn't parse empty message.
> Fix malformed packet when no arguments provided

- pythonosc/parsing/ntp.py
- pythonosc/parsing/osc_types.py
- pythonosc/test/parsing/test_osc_types.py
With the original implementation, i permanently got "late ..." messages when sending OSC bundles to ScSynth (locally) , even with half a second latency added.
So i ported the implementation from the OSC module, as found here:
http://trac.assembla.com/pkaudio/browser/scosc/tools.py#L105
With the changed implementation, there are no more "late ..." messages in SySynth, even with latencys as small as 10ms.
> ntp timestamp conversion seems to be off ... 

- pythonosc/osc_message_builder.py
```
>>> isinstance(True, int)
True
```
See https://stackoverflow.com/questions/37888620/python-comparing-boolean-and-int-using-isinstance
> Correctly set the message type for booleans

- pythonosc/osc_message.py
- pythonosc/parsing/osc_types.py
- pythonosc/test/parsing/test_osc_types.py
- pythonosc/test/test_osc_message.py
added the case 't' to osc_message.py in order to properly handle ttag parsing in osc_types.py for use in client application (otherwise client applications crash if this type of data shows up).
> can now parse osc time tags

- pythonosc/parsing/osc_types.py
osc_types causes printing timestamp each time a OSC bundle was created
> osc_types.py: remove print statement

- .travis.yml
- pythonosc/dispatcher.py
- pythonosc/test/test_dispatcher.py
I noticed that there was no way to unmap handlers from addresses, so I added one. Comes with unit test.
> Add unmap method to dispatcher

- README.rst
There's no reason to import osc_message_builder in the simple client example, and it was missing from the building bundles examples.
> Correct imports on README examples

- pythonosc/udp_client.py
The UDP client does not support IPv6 connections at the moment. This change would fix that.
> Add support for IPv6 to UDPClient

- pythonosc/osc_message_builder.py
- pythonosc/test/test_osc_message_builder.py
- pythonosc/udp_client.py
This would allow the client to send NIL values. The result should be identical to what can be achieved with oscsend: 
oscsend osc.udp://host:1234 /device/1/2/3
To send such a value, use:
client.send_message("/device/1/2/3", None)
> Add support for sending NIL value

- pythonosc/osc_message.py
- pythonosc/osc_packet.py
- pythonosc/parsing/ntp.py
- pythonosc/parsing/osc_types.py
- pythonosc/test/parsing/test_ntp.py
- pythonosc/test/parsing/test_osc_types.py
Hi
OSC timetag conversion was broken. This PR solves that problem and TimedMessage not being scheduled from bundles by Dispatcher.call_handlers_for_packet().
I did change some names to make them more meaningful (at least for me). If that is not acceptable you can still take the timing fix from this patch and have my approval.
> Fix ntp/osc timestamp/timetag conversion and TimedMessage time.

- .travis.yml
- pythonosc/udp_client.py
Switch from deprecated `from collections import Iterable` to `from collections.abc import Iterable` for python 3.8 support.
> In python 3.8, Iterable must be imported from collections.abc

- CHANGELOG.md
- README.rst
- pythonosc/osc_message.py
- pythonosc/osc_message_builder.py
- pythonosc/parsing/osc_types.py
- pythonosc/test/test_osc_message.py
- pythonosc/test/test_osc_message_builder.py
I have implemented the long requested Int64 support in #21 . I followed the code style of the `UInt64` and `Integer` implementation.
Here is an example script to test it, unit tests are implemented as well.
```python
import threading
import time
from pythonosc.dispatcher import Dispatcher
from pythonosc.osc_message_builder import OscMessageBuilder
from pythonosc.udp_client import SimpleUDPClient
from pythonosc import osc_server
HOST = "127.0.0.1"
PORT = 7500
ADDRESS = "/test"
def start_listener():
dispatcher = Dispatcher()
dispatcher.map(ADDRESS, print)
server = osc_server.ThreadingOSCUDPServer(
(HOST, PORT), dispatcher)
print("Serving on {}".format(server.server_address))
server.serve_forever()
def main():
threading.Thread(target=start_listener).start()
sender = SimpleUDPClient(HOST, …
```
> Add Int64 support (OSC Type h)

- .github/workflows/python-test.yml
- README.rst
- examples/async_server.py
- examples/reaktor_lazerbass.py
- examples/simple_2way.py
- examples/simple_server.py
- pythonosc/dispatcher.py
- pythonosc/osc_bundle.py
- pythonosc/osc_bundle_builder.py
- pythonosc/osc_message.py
- pythonosc/osc_message_builder.py
- pythonosc/osc_packet.py
- pythonosc/osc_server.py
- pythonosc/parsing/ntp.py
- pythonosc/parsing/osc_types.py
- pythonosc/test/test_osc_server.py
- pythonosc/udp_client.py
- setup.cfg
This adds type checking in CI with `mypy`, a basic configuration for `mypy` and fixes the errors that are found.
The configuration is very nearly the default and mostly doesn't enable additional checks. The checks which are enabled are mostly to guide future usage in the right direction.
The fixes here are intended to be as minimal as possible and are derived from code inspection. I've run the tests, but don't have an actual deployment to test this with manually.
> Add type checking in CI and fixup annotations

- MANIFEST.in
This allows type checkers to make use of the types from this package when validating consuming code.
Fixes https://github.com/attwad/python-osc/issues/155
> Indicate that this is a typed package

- .github/workflows/python-test.yml
They're not floats, which YAML would try to treat them as by default.
> Treat Python versions as strings

- pythonosc/osc_message.py
- pythonosc/osc_message_builder.py
- pythonosc/osc_server.py
- pythonosc/test/test_osc_message.py
- pythonosc/test/test_osc_message_builder.py
This PR adds support for creating and parsing messages with a `Nil` argument type. Arguments of `Nil` type are mapped to a python `None` (and vice versa).
I have added unit tests for the new functionality, and verified third-party compatibility by sending/receiving messages containing nil parameters with `liblo`.
I needed this for some features I'm developing for [AbletonOSC](https://github.com/ideoforms/AbletonOSC), in which OSC endpoints need to return lists of arguments which may contain one or more nil values.
Thanks for the great library!
> Add support for arguments with Nil type

- pythonosc/udp_client.py
If getaddrinfo returns multiple addresses, udp_client always chooses the first one for which it can create a socket. So if I have a server on a machine set to listen to e.g. "0.0.0.0", and the client refers to the machine by name, there is a possibility that it will choose an IPv6 address, and the two will fail to connect. This simple addition allows the user of the UdpClient to require one or the other.
> Add options to UdpClient to force the use of IPv4 when IPv6 is available and vice versa

- .gitignore
- CHANGELOG.md
- docs/client.rst
- docs/dispatcher.rst
- docs/server.rst
- examples/async_simple_tcp_client.py
- examples/async_tcp_server.py
- examples/simple_echo_client.py
- examples/simple_echo_server.py
- examples/simple_tcp_client.py
- examples/simple_tcp_server.py
- pythonosc/dispatcher.py
- pythonosc/osc_message.py
- pythonosc/osc_message_builder.py
- pythonosc/osc_server.py
- pythonosc/osc_tcp_server.py
- pythonosc/slip.py
- pythonosc/tcp_client.py
- pythonosc/test/test_osc_server.py
- pythonosc/test/test_osc_tcp_server.py
- pythonosc/test/test_tcp_client.py
- pythonosc/udp_client.py
Added support for TCP client and server, using both the 1.0 "length" protocol and the (default) 1.1 SLIP protocol.
Blocking/threaded and asyncio implementation are available for client and server.
Examples and tests are included.  Basic functional testing of the client was done using QLab 5.4.4 and Eos 3.2.7, and I verified that it is possible to trigger cues in both using a TCP client. 
Fixes #52
> Add tcp support

- examples/simple_2way.py
- examples/simple_echo_server.py
- examples/simple_server.py
- examples/simple_tcp_server.py
- pythonosc/dispatcher.py
- pythonosc/osc_bundle.py
- pythonosc/osc_bundle_builder.py
- pythonosc/osc_message.py
- pythonosc/osc_message_builder.py
- pythonosc/osc_packet.py
- pythonosc/parsing/osc_types.py
- scripts/print_datagrams_main.py
Since this project targets Python 3.10, this PR transforms `%` interpolation and `.format()` calls to f -strings.
The two first commits are made mechanically with [flynt](https://github.com/ikamensh/flynt), the last was made by hand.
> Use f-strings for formatting

- .github/workflows/python-test.yml
Includes a CI check that the published types are recognised. This PR contains a CI run for just that commit, validating the expected failure mode.
Fixes https://github.com/attwad/python-osc/issues/182
> Publish type annotations

- pythonosc/osc_tcp_server.py
- pythonosc/test/test_osc_tcp_server.py
As mentioned in issue 176, according to the documentation one of the ways a callback function may pass a reply back to a client is by returning a message encapsulated thusly: `tuple(<Address>, <ArgValue>)`.
Whilst the code for the UDP servers does conform to this, the code to TCP servers was expecting `list(<Address>, <ArgValue>)` in all cases.
This PR resolves that, updating the tests as well.
Fixes #176
> Expect Dispatcher replies for TCP to be tuples, not lists
